# Generated by Django 4.2.5 on 2023-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_alter_todo_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated',
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
